name: Flutter CI/CD

on:
  push:
    branches: ["**"]

jobs:

  build_android:
    name: Build Android
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Enable Git long paths
        run: git config --system core.longpaths true
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b 3.32.5 _flutter
      - name: Get Packages
        run: ${{ github.workspace }}\_flutter\bin\flutter.bat pub get
      - name: Build Android APK
        run: ${{ github.workspace }}\_flutter\bin\flutter.bat build apk --release
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: build/app/outputs/flutter-apk/app-release.apk

  build_web:
    name: Build Web
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Enable Git long paths
        run: git config --system core.longpaths true
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b 3.32.5 _flutter
      - name: Get Packages
        run: ${{ github.workspace }}\_flutter\bin\flutter.bat pub get
      - name: Build Web
        run: ${{ github.workspace }}\_flutter\bin\flutter.bat build web --release
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: build/web/

#  build_ios:
#    name: Build iOS
#    runs-on: macos-latest
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#      - name: Set up JDK 17
#        uses: actions/setup-java@v1
#        with:
#          java-version: "17.x"
#      - name: Install Flutter
#        uses: subosito/flutter-action@v1
#        with:
#          flutter-version: '3.32.5'
#      - name: Get Packages
#        run: flutter pub get
#      - name: Build iOS
#        run: flutter build ios --no-codesign
